### ISSUE TITLE
Add support to register apps with its companion resource

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1069]
Split into #1135 #1136 #1137. This should be considered the umbrella story. 

As a developer, I'd like to enhance `app register` and `app import` commands to be used with an extra inline property `--metadata` (or something similar), so this property can point to the URI of the artifact that includes application metadata and whitelisted properties alone. 

**Benefits:**
- Both the docker and maven application artifacts can support commands like `app info`. 
- This change improves the overall efficiency by not downloading the entire application artifact in order to view the `app info` details. The application is only downloaded and cached upon stream deployments. 

**Acceptance:**
- a new inline property (`--metadata`?) is now supported for both `app register` and `app import` (indirectly through the imported file) commands 
- issuing `app info .. ` downloads just the app metadata and _not_ the entire application artifact 
- issuing `app info .. ` repeatedly loads the app metadata from cache
- unit-tests included
- relevant references in the reference guide is updated with the change ("breaking change" note is added)
- scdf's server implementation docs are reviewed and updated

Dependent stories:
- [x] spring-cloud/spring-cloud-dataflow#1135
- [x] spring-cloud/spring-cloud-dataflow#1136
- [x] spring-cloud/spring-cloud-dataflow#1137

**Comment by ilayaperumalg** [comment]
Does this mean the apps (including the OOTB apps) would need to have the generated jars with the actual `executable` jar and the `metadata` jar with the configuration data json/whitelisted properties? If so, the pre-cursor story would be to generate `metadata` jars for the apps.

**Comment by trisberg** [comment]
Yes, this depends on having this extra artifact generated for the OOTB apps. Without registering this extra artifact everything should work as it does today, pulling out the metadata from the maven jar for maven resources and having no metadata for docker ones.

**Comment by sabbyanandan** [comment]
Addressed via https://github.com/spring-cloud/spring-cloud-dataflow/commit/c0d902a0b72420d5b7499881e178f31dff041f9f.
