### ISSUE TITLE
Backport to 1.6.4

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#2471]
- [ ] #2469 - Add TaskDefinition support to `ArgumentSanitizer`
- [x] #2478 - Update app starter versions in ref docs to latest
- [ ] #2508 - App info cmd issue on using <type:name>

**Comment by ilayaperumalg** [comment]
Cherry-picked and pushed #2478 into 1.6.x as 40dceaf4

**Comment by sabbyanandan** [comment]
These are already applied in 1.7.x and 2.0.x, so we won't have to continue to maintain on 1.6.x.
