### ISSUE TITLE
Epic: Make OAuth2/OpenID Connect the only security option

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#2574]
- [x] Update Security Dependencies to Spring Security `5.1.x` (Part of Boot `2.1.x`)
- [x] Local Server: Provide CF UAA as the default provider for local security (UAA Team)
  - Ensure easy bundling/bootstrapping of the UAA
- [x] Local Server: Provide Documentation on how to setup and use the UAA  (UAA Team)
  - Document persistence store options with the UAA
- [x] Remove LDAP related code
- [x] Remove the option to disable `Authorization`
- [x] Remove File Based Authentication
- [x] Remove traditional security option
  - When authentication is enabled, then authorization shall always be enabled
  - Security will be disabled by default 
- [x] Provide documentation on how to use LDAP authentication with the UAA
  - Refactor existing documentation
- [x] Provide example application that shows LDAP authentication in action
- [x] Consider removing Username+Password authentication for the SCDF Shell
  - Add option to start the shell with just an Access Token (in addition to `--dataflow.credentials-provider-command`)
  - Provide documentation on how to get and provide an Access Token
- [x] Revisit security for Composed Task Runner
- [x] Revisit Skipper security integration
- [x] Revisit `taskLauncher-dataflow` security integration
- [x] Refactor security code that can be shared with other projects (e.g. Skipper) to Spring Cloud Common Security
- [x] Refactor the documentation regarding Role Mapping (we would have to think about backward compatibility -> `SCOPE_` vs. `ROLE_`)
- [x] Add new roles (i.e: ROLE_SCHEDULE, ROLE_DEPLOY, ROLE_DESTROY)
- [x] Provide explicit support for `Client Credentials grant type` (Service-to-Service integrations)
  - Provide options in regards to role assignments (since `Client Credentials grants` operation outside of OpenID Connect)
~- [ ] Migrate from RestTemplate to WebClient (OAuth support is provided for WebClient but not RestTemplate which is (almost) considered deprecated)~
~- [ ] Refactor old Spring Security OAuth Infrastructure (required for the test-support)~
  ~- Consider Lack of Authorization Server in Spring Security 5.1/5.2 (Use embedded UAA?)~
- [x] Refactor LDAP tests to use UAA? as the backend

Is also depended on by https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/984
