### ISSUE TITLE
Backport commits to 2.0.x 

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3118]
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/issues/3040 - Multiple TaskPlatform configuration requires setting multiple active profiles to be enabled (still WIP on master)
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/issues/3036 - Revisit arch diagram - eaa5b57aa1d33bf3a48cc83a28ac2318daab7016 on 2.0.x branch
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/issues/3009 - Update docs for enabling Kafka in Helm chart - c5ab24d021352e11ee54effe3b45ec54f31c132c on 2.0.x branch

- [x] https://github.com/spring-cloud/spring-cloud-dataflow/issues/3117 -  8ddd2043909e67eb5d4348f98a471cf4addf0b7a Updated doc to fix version replacement in shell download command

- [x] https://github.com/spring-cloud/spring-cloud-dataflow/issues/3113 - f5b323470959fce026680519ce08a1536dbe0cbc Rename schedulerEnabled -> schedulesEnabled in About info

- [x] https://github.com/spring-cloud/spring-cloud-dataflow/issues/3019 - 8f6ca558fec67e0bbe1a1e9159e078b2f1750578 Remove H2 related task configs

- [x] https://github.com/spring-cloud/spring-cloud-dataflow/commit/4c789f4a5ea16e27a3389b4155d3b300dca4657d
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/commit/8ddd2043909e67eb5d4348f98a471cf4addf0b7a
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/issues/2869 Need to verify fix cd6b90fcd0b5fb0bdef92dd155ce933aecd35583 fromDate and toDate format changed in AuditRecordController#list Using DateTimeFormatter.ISO_DATE_TIME with ZoneOffset.UTC
- [x] https://github.com/spring-cloud/spring-cloud-dataflow/issues/3005 d20f0dd9f45ec28e87bdc1a0c1d2ae705840928f Validate app names for their length

- [x] #3108 - 278d13f77c0de691bb424899bb675b9039f113bb (HEAD -> 2.0.x, upstream/2.0.x) Use sl4fj for logging in all the classes

**Comment by sabbyanandan** [comment]
All the targeted backports are complete. Marking it as done.
