### ISSUE TITLE
Epic: Move to Boot/Cloud 2.2.x family

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3399]
The SCDF v2.3 stack will use Boot/Cloud v2.2 as the foundation. There are several dependencies to synchronize as part of this effort.

- [x] Switch to Spring Cloud Build 2.2 SNAPSHOTs (2.2 M2 is available also) -- bring Boot with it.
- [x] Upgrade all the deployers to this foundation (schedulers will be merged into deployers)
- [x] Upgrade Skipper 
- [x] Switch to Spring Cloud Task 2.2 SNAPSHOTs
- [x] Upgrade CTR
- [ ] Upgrade Task Launcher Dataflow
- [x] Upgrade Security Commons
- [x] Make sure ATs are run on SCDF 2.3 SNAPSHOTs (perhaps also branch old version)
- [x] Microsite chores
- [x] Anything in DB testing in regards to Data/JPA changes?
- [ ] Document breaking changes if any
- [x] Create CI plans
- [ ] ...

**Comment by sabbyanandan** [comment]
Other than security (which is tracked in a different story), all the remaining chores of this epic is complete.
