### ISSUE TITLE
Retest security integration in SCDF components

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3591]
- [x] Test CTR - @ghillert (see: https://github.com/spring-cloud-task-app-starters/composed-task-runner/issues/102)
- [x] Test TaskLauncher DF - @ghillert  (see: https://github.com/spring-cloud-stream-app-starters/tasklauncher-dataflow/issues/23)
- [x] Scheduling DF (new - @jvalkeal)
~- [ ] SCDF Tile - @mheath~

**Comment by sabbyanandan** [comment]
@mheath: All OK on your end on the latest changes? If you have see any anomlaies, please let us know.

**Comment by sabbyanandan** [comment]
The CTR, TL-DF, Scheduling components were tested against the new security changes. 

The tile, however, it remains unverified. @mheath: if you see any issues with the integration, please let us know. 

Closing this epic as complete.
