### ISSUE TITLE
Add platform support for schedules.

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#3944]
- [ ] Add Restful api call to retrieve platforms that support schedules
- [ ] Add platform selection to restful api schedule create request
- [ ] add platform selection for listing schedule
- [ ] add platform selection fro deleting schedule
- [ ] Add platform support for deleting all schedules across all platforms when deleting a task definition. 
- [ ] Add platform selection for these calls to shell request.
