### ISSUE TITLE
Increase Batch/Task IT test coverage

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#4594]
The following tests need to be added to SCDF IT tests.
- [x] Launch Batch Job and verify it was successful
- [x] Launch Batch Job that fails and verify that it can be restarted
- [x] Launch Batch Job that succeeds and verify that it can't be restarted.
- [x] Verify that Batch Job Steps, are obtainable.
- [x] Upgrade Task App version
- [x] Rollback Task App version
- [x] Launch task with properties and make sure properties are re-used.
- [x] Launch Invalid task definition
- [x] Launch Task with arguments.   Relaunch and verify that they are not used on subsequent launches.
- [x] Verify Task Definition deletion
- [x] Vefify Task Deletion with cleanup.
