### ISSUE TITLE
Ensure reference doc is up-to-date and valid

### ISSUE THREAD

**Issue by onobc** [spring-cloud/spring-cloud-dataflow#4807]
1. [x] Remove all reference to stream/task-app-starters and replace w/ stream-applications
2. [x] Replace all links pointing to `master` w/ `main`
3. [x] Make sure all links to libs and jars are valid

**Comment by onobc** [comment]
**5.1. Application and Server Properties**

> Properties to be applied for all deployed Tasks are defined in the src/kubernetes/server/server-config-[binder].yaml file and for Streams in src/kubernetes/skipper/skipper-config-[binder].yaml. Replace [binder] with the messaging middleware you are using — for example, rabbit or kafka.

**PROBLEM**: invalid path/name of files.

**Comment by onobc** [comment]
**5. Getting Started - Kubernetes**

**PROBLEM**: Why the detail here but not w/ the other Local/CF? Those just point to the Microsite.

**Comment by onobc** [comment]
**7.1. Wagon**

**QUESTION:** Any updates needed here wrt to the recent CVE ?

**Comment by onobc** [comment]
**8. Security**

**QUESTION:** Is the following still valid?

> While you can theoretically choose any OAuth provider in conjunction with Spring Cloud Data Flow, we recommend using the CloudFoundry User Account and Authentication (UAA) Server.
> 
> Not only is the UAA OpenID certified and is used by Cloud Foundry, but you can also use it in local stand-alone deployment scenarios. Furthermore, the UAA not only provides its own user store, but it also provides comprehensive LDAP integration.

**Comment by onobc** [comment]
8.1. Enabling HTTPS
8.2. Authentication by using OAuth 2.0
8.3. Customizing Authorization
8.4. Setting up UAA Authentication

**TODO** Validate the steps work as expected

**Comment by onobc** [comment]
**9.2 Database**

**TODO:** Scan through the entire section, still valid?

**Comment by onobc** [comment]
**17.1.1. Register Supported Applications and Tasks**

**Spring Cloud Stream App Starters**

> The following table includes the dataflow.spring.io links to the available Stream Application Starters based on Spring Cloud Stream 2.1.x and Spring Boot 2.1.x:


**OLD**

> 	Starting with the Spring Cloud Stream 2.1 GA release, we now have robust interoperability with the Spring Cloud Function programming model. Building on that, with the Einstein release-train, it is now possible to pick a few Stream App Starters and compose them into a single application by using the functional-style programming model. Check out the "Composed Function Support in Spring Cloud Data Flow" blog to learn more about the developer and orchestration-experience with an example.

**Spring Cloud Task App Starters**
Ditto - links are going to Einstein release things.

**Comment by onobc** [comment]
**22. Functional Applications**

> With Spring Cloud Stream 3.x adding functional support, you can build Source, Sink and Processor applications merely by implementing the Java Util’s Supplier, Consumer, and Function interfaces respectively. See the Functional Application Recipe of the SCDF site for more about this feature.

**TODO:** We should just remove this as its the default now

**Comment by onobc** [comment]
Closed via https://github.com/spring-cloud/spring-cloud-dataflow/commit/22d4b32037172c9ffff8e1907b0909de647b2abf
